# Generated by Django 4.2 on 2023-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
